# Generated by Django 5.2.4 on 2025-07-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firreport',
            name='citizenship_back',
            field=models.ImageField(blank=True, null=True, upload_to='fir_citizenship/'),
        ),
        migrations.AddField(
            model_name='firreport',
            name='citizenship_front',
            field=models.ImageField(blank=True, null=True, upload_to='fir_citizenship/'),
        ),
        migrations.AddField(
            model_name='firreport',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='fir_photos/'),
        ),
    ]
