# Generated by Django 5.2.4 on 2025-07-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0002_firreport_citizenship_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firreport',
            name='custom_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firreport',
            name='subject',
            field=models.CharField(choices=[('murdering', 'Murdering'), ('sexual_harassment', 'Sexual Harassment'), ('corruption', 'Corruption'), ('miss_behave', 'Miss-behave'), ('cyber_crime', 'Cyber Crime'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fir_evidence/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fir_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_images', to='FIR.firreport')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
